Account/urls.py
from django.urls import path
from Account.views import (
    account_view,
    edit_account_view,
)
app_name = 'account'
urlpatterns = [
    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name="edit")
]

freelancer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from Account.views import (
    registration_view,
    logout_view,
    login_view,
)

from home.views import home, job_posting,list_jobs,list_all_jobs,job_detail,ai_jobs


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('job_posting/', job_posting, name="job_posting"),
    path('list_jobs/', list_jobs, name="list_jobs"),
    path('list_all_jobs/', list_all_jobs, name="list_all_jobs"),
    path('ai_jobs/', ai_jobs, name="ai_jobs"),
    path('job_detail/<int:job_id>/', job_detail, name="job_detail"),
    path('account/', include('Account.urls', namespace='account')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', registration_view, name="register"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_changedone.html'),
    name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_resetdone.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_resetform.html'),
        name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_resetcomplete.html'),
        name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.conf import settings

class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200,null=True)
    email = models.CharField(max_length=200,null=True)
    phone = models.CharField(max_length=12,null=True,unique=True)
    def __str__(self):
        return self.name
    
def get_post_image_filepath(self, filename):
    return 'post_images/' + str(self.pk) + '/post_image.png'
    
class Posting(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200,null=True)
    abstract = models.TextField(null=True)
    detail_description = models.TextField(null=True)
    skills = models.CharField(max_length=200,null=True)
    budget = models.CharField(max_length=200,null=True)
    image = models.ImageField(max_length=255,upload_to=get_post_image_filepath,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model
from Account.models import Account
from home.models import Posting
from dotenv import load_dotenv
from langchain.text_splitter import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import DeepLake
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from langchain_openai import ChatOpenAI
import os
load_dotenv()
user=get_user_model()

openai_api_key = os.getenv('OPENAI_API_KEY')
def get_pdf_text():
    text = """Problem Statement:
Establish a platform that connects freelancers with potential clients, enhancing visibility and
opportunities.

Solution:

Title: Bridging the Gap: How Our Platform Connects Freelancers with Clients Seamlessly

In todays dynamic digital landscape, the demand for freelance services is booming. From graphic design
to content creation, businesses are increasingly turning to freelancers to meet their diverse needs.
However, with this surge in demand comes a new set of challenges for both freelancers and clients alike.
Finding the right match can be time-consuming and frustrating, often leading to missed opportunities and
underutilized talents.

Enter our innovative platform, designed to bridge the gap between freelancers and clients, revolutionizing
the way they connect and collaborate. Heres how it works:

* Comprehensive Profile Creation: Freelancers are invited to create detailed profiles showcasing their
skills, experience, and portfolio. Clients, on the other hand, can create profiles outlining their specific
project requirements and expectations.

* Advanced Search and Filtering: Our platform utilizes advanced search algorithms to match freelancers
with projects that align with their expertise and interests. Clients can easily filter through profiles based on
criteria such as skills, experience level, and budget.

* Real-time Communication: Once a potential match is identified, our platform facilitates seamless
communication between freelancers and clients through integrated messaging tools. This allows for
efficient collaboration and ensures that both parties are on the same page from the outset.

* Resource Center and Support: In addition to facilitating connections, our platform serves as a valuable
resource center for freelancers and clients alike. From best practices for project management to tips for
negotiating contracts, our platform offers comprehensive support every step of the way.

* Continuous Improvement: We are committed to continuously improving our platform based on user
feedback and industry trends. Through regular updates and enhancements, we strive to provide the best
possible experience for freelancers and clients alike.

In conclusion, our platform offers a user-friendly and efficient solution to the challenges of connecting
freelancers with clients. By leveraging cutting-edge technology and fostering a supportive community, we
empower freelancers to showcase their talents and help clients find the perfect match for their projects.
Join us and experience the future of freelance collaboration today!

 """
    return text

def get_text_chunks(text):
    text_splitter = CharacterTextSplitter(
        separator = "\n",
        chunk_size=1000,
        chunk_overlap=150,
        length_function=len
    )
    chunks = text_splitter.split_text(text)
    return chunks

def get_vectorstore(text_chunks):
    dataset_path = "./my_deeplake/"
    embeddings = OpenAIEmbeddings()
    vectorstore = DeepLake.from_texts(text_chunks,dataset_path=dataset_path, embedding=embeddings)
    return vectorstore

def get_conversation_chain(vectorstore,user_question):
    llm = ChatOpenAI(model="gpt-3.5-turbo")
    memory = ConversationBufferMemory(memory_key='chat_history')
    conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        memory=memory,
        retriever=vectorstore.as_retriever(),
    )
    user_question += 'Draft the response in less than 50 words.'
    response = conversation_chain({'question':user_question})
    return response['answer']

def home(request):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    if request.method == 'POST':
        user_question = request.POST['chatinput']
        raw_text = get_pdf_text()
        text_chunks = get_text_chunks(raw_text)
        vectorstore = get_vectorstore(text_chunks)
        response = get_conversation_chain(vectorstore,user_question)
        context['content'] = response
        DeepLake.force_delete_by_path("./my_deeplake/")

    return render(request, 'home/home.html',context)

def job_posting(request):
    user_id = request.user.id
    customer = request.user.customer
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    if request.method == 'POST':
        Posting.objects.create(
            customer=customer,
            title=request.POST['title'],
            abstract=request.POST['abstract'],
            detail_description=request.POST['description'],
            skills=request.POST['skills'],
            budget=request.POST['budget'],
            image=request.FILES['image']
        )
        return redirect('home')
    return render(request, 'home/job_posting.html',context)

def list_jobs(request):
    user_id = request.user.id
    customer = request.user.customer
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass
    context['jobs'] = Posting.objects.filter(customer=customer)
    return render(request, 'home/list_jobs.html',context)

def list_all_jobs(request):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    if request.method == 'POST':
        context['jobs'] = Posting.objects.filter(title__contains=request.POST['search'])
    else:
        context['jobs'] = Posting.objects.all()
    return render(request, 'home/list_all_jobs.html',context)

def job_detail(request,job_id):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass
    context['job'] = Posting.objects.get(pk=job_id)
    return render(request, 'home/job_detail.html',context)

def ai_jobs(request):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    return render(request, 'home/ai_jobs.html',context)

home/templates/home/ai_posts.html
{% extends 'home/main.html' %}
{% load static %}
{% block content %}

{% endblock content %}

home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>FreelanceGo</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        body{
            font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .logo-label {
            color: #000;
            justify-content: center;
        }
        .navbar {
            font-size: 22px;
            background-color: #f9f8f8;
            height: 60px;
        }
        .nav2 {
            font-size: 22px;
            background-color: #556063;
            margin:0;
            height: 40px;
            color: white;
        }
        .container {
            display: flex;
            justify-content:space-between;
        }
        .container2 {
            display: flex;
            justify-content:center;
        }
        .nav-links {
            list-style-type: none;
            justify-content: center;
            display: flex;
            color: black; /* Set text color to black */
        }
        .nav-links-2 {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
            color: rgb(255, 252, 252); /* Set text color to black */
        }
        .nav-links li {
            margin-right: 20px;
        }
        .nav-links-2 li {
            margin-right: 20px;
        }
        .nav-links li a {
            color: black; /* Set link text color to black */
            text-decoration: none;
        }
        .nav-links-2 li a {
            color: rgb(255, 255, 255); /* Set link text color to black */
            text-decoration: none;
        }
        .login-btn {
            background-color: blue;
            color: white;
            padding: 8px 16px;
            border-radius: 4px;
            margin-right: 20px; /* Add margin to separate it from other links */
        }
        .nav-signups {
            list-style-type: none;
            justify-content: center;
            padding-right: 30px;
        }
        .nav-signups li button {
            background-color: #4c9daf; /* Green */
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;

            cursor: pointer;
            border-radius: 20px; /* Rounded corners */
            transition: background-color 0.3s ease; /* Smooth transition */
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Shadow for depth */
        }
        .nav-signups li button:hover {
            background-color: #45a049; /* Darker green on hover */
        }
        #chat-container {
        position: fixed;
        bottom: 70px; /* initial position */
        right: 20px;
        width: 300px;
        display: none;
        }

        #toggle-chat-btn {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 1000;
        }

        #chat-container.hidden {
        display: block;
        }
    </style>
</head>
<body style="margin: 0;">
        {% include 'home/snippets/navbar.html' %}
        <nav class="nav2">
            <div class="container2">
                <ul class="nav-links-2">
                    <li><a style="text-decoration: none;font-size: 20px;font-weight: 400;" href="#home">Home</a></li>
                    <li><a style="text-decoration: none;font-size: 20px;font-weight: 400;" href="#about">About</a></li>
                    <li><a style="text-decoration: none;font-size: 20px;font-weight: 400;" href="#testimonials">Testimonials</a></li>
                    <li><a style="text-decoration: none;font-size: 20px;font-weight: 400;" href="#footer">Contact</a></li>
                </ul>
            </div>
        </nav>
        
        <div class="container-fluid p-0" id="home">
            <div class="position-relative">
                <img class="img-fluid" src="{% static 'images/carousel-2.jpg' %}" alt="" style="width: 100%;">
                <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(43, 57, 64, .5);">
                    <div class="container">
                        <div class="row justify-content-start">
                            <div class="col-10 col-lg-8">
                                <h1 class="display-3 text-white animated slideInDown mb-4">Connecting Talent with Opportunity</h1>
                                <p class="fs-5 fw-medium text-white mb-4 pb-2">Find the perfect freelancer or showcase your skills today!</p>
                                <a href="{% url 'list_jobs' %}" style="color: #e8ce4d; background-color: #212529;" class="btn py-md-3 px-md-5 me-3 animated slideInLeft">Find A Talent</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-xxl py-5" id="about">
            <div class="container">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                        <div class="row g-0 about-bg rounded overflow-hidden">
                            <div class="col-6 text-start">
                                <img class="img-fluid w-100" src="{% static 'images/about-1.jpg' %}">
                            </div>
                            <div class="col-6 text-start">
                                <img class="img-fluid" src="{% static 'images/about-2.jpg' %}" style="width: 85%; margin-top: 15%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid" src="{% static 'images/about-3.jpg' %}" style="width: 85%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid w-100" src="{% static 'images/about-4.jpg' %}">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                        <h1 class="mb-4">We Help To Get The Best Job And Find A Talent</h1>
                        <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Tempor erat elitr rebum at clita</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Aliqu diam amet diam et eos</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Clita duo justo magna dolore erat amet</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-xxl py-5" id="testimonials">
            <div class="container" style="display: flex;">
                <div class="row">
                    <div class="col-12">
                        <h1 class="text-center mb-5">Our Clients Say!!!</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light rounded p-4">
                            <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                            <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                            <div class="d-flex align-items-center">
                                <img class="img-fluid flex-shrink-0 rounded" src="{% static 'images/testimonial-3.jpg' %}" style="width: 50px; height: 50px;">
                                <div class="ps-3">
                                    <h5 class="mb-1">Sri Manikandan R</h5>
                                    <small>Backend Developer</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="chat-container" class="card hidden">
            <div class="card-header">
              Chatbot
            </div>
            <div class="card-body container-fluid">
                {{content}}
            </div>
            <div class="card-footer">
              <div class="input-group">
                <form method="post">{% csrf_token %}
                    <input type="text" id="chatinput" name="chatinput" class="form-control" placeholder="Type your message...">
                    <div class="input-group-append">
                      <button id="send-btn" class="btn" style="background-color: #212529;color: #e8ce4d;">Send</button>
                    </div>
                </form>
              </div>
            </div>
          </div>
          <button id="toggle-chat-btn" class="btn" style="background-color: #212529;color: #e8ce4d;">Open Chat</button>
        {% include 'home/snippets/footer.html' %}
        <script src="{% static 'js/main.js' %}"></script>
</body>
</html>
    

home/templates/home/job_detail.html
{% extends 'home/main.html' %}
{% load static %}
{% block content %}
    <div class="container" style="width: 600px;border: 2px solid black;margin-top: 30px; border-radius: 10px;padding: 10px;">
        <div class="row">
            <div class="col-12">
                <img src="{{ job.image.url }}" class="img-fluid" alt="...">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h3><b>Project Title: </b><span style="font-weight: 400;">{{ job.title }}</span></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p><b>Abstract: </b>{{ job.abstract }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p><b>Description: </b>{{ job.detail_description }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p><b>Skills Required:</b> {{ job.skills }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p><b>Budget:</b> ${{ job.budget }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

home/templates/home/job_posting.html
{% extends 'home/main.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top: 50px;">
    <div class="row" style="margin-bottom: 30px;">
        <div class="col-12">
            <h1 class="text-center">Job Posting</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12" style="display: flex;justify-content: center;">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Project Title</label>
                    <input type="text" class="form-control" id="id_title" name="title" placeholder="Enter title">
                    <label for="id_abstract">Project Abstract</label>
                    <textarea class="form-control" id="id_abstract" name="abstract" placeholder="Enter abstract"></textarea>
                    <label for="id_description">Project Description</label>
                    <textarea class="form-control" id="id_description" name="description" placeholder="Enter description"></textarea>
                    <label for="id_skills">Skills Required</label>
                    <input type="text" class="form-control" id="id_skills" name="skills" placeholder="Enter skills">
                    <label for="id_image">Project Image</label>
                    <input type="file" class="form-control" id="id_image" name="image" placeholder="Enter image">
                    <label for="id_budget">Budget</label>
                    <input type="number" class="form-control" id="id_budget" name="budget" placeholder="Enter budget">
                    <div style="display: flex;justify-content: center;">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/home/list_all_jobs.html
{% extends 'home/main.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top: 50px;">
    <div class="row" style="margin-bottom: 30px;">
        <div class="col-12">
            <h1 class="text-center">All Jobs</h1>
        </div>
    </div>
    <div class="row" style="margin-bottom: 30px;" style="display: flex;justify-content: center;width: 800px;">
        <form class="d-flex" method="post" role="search">{% csrf_token %}
            <input class="form-control me-2" type="search" name="search" id="search" placeholder="Search" aria-label="Search">
            <div style="display: flex;justify-content: center;">
                <button class="btn btn-lg btn-block" style="width: 200px;background-color: #212529;color: #e8ce4d;" type="submit">Search</button>
            </div>
        </form>
    </div>
    <div class="row" style="display: flex;justify-content: space-evenly;">
        {% for job in jobs %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card mb-4">
                <img src="{{ job.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ job.title }}</h5>
                    <p class="card-text">{{ job.abstract }}</p>
                    <a href="{% url 'job_detail' job_id=job.id %}" class="btn btn-primary">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

home/templates/home/list_jobs.html
{% extends 'home/main.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top: 50px;">
    <div class="row" style="margin-bottom: 30px;">
        <div class="col-12">
            <h1 class="text-center">My Jobs</h1>
        </div>
    </div>
    <div class="row" style="display: flex;justify-content: space-evenly;">
        {% for job in jobs %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card mb-4">
                <img src="{{ job.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ job.title }}</h5>
                    <p class="card-text">{{ job.abstract }}</p>
                    <a href="{% url 'job_detail' job_id=job.id %}" class="btn btn-primary">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

home/templates/home/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Freelancego</title>
</head>
<body>
    {% include 'home/snippets/navbar.html' %}
    <style type="text/css">
        .main {
            min-height: 50vh;
            height: 100%;
        }
    </style>
    <div class="main container">
        {% block content %}
 
        {% endblock content %}
    </div>
    {% include 'home/snippets/footer.html' %}
</body>
</html>