Account/urls.py
from django.urls import path
from Account.views import (
    account_view,
    edit_account_view,
)
app_name = 'account'
urlpatterns = [
    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name="edit")
]

freelancer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from Account.views import (
    registration_view,
    logout_view,
    login_view,
)

from home.views import home, job_posting,list_jobs,list_all_jobs,job_detail,ai_jobs


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('job_posting/', job_posting, name="job_posting"),
    path('list_jobs/', list_jobs, name="list_jobs"),
    path('list_all_jobs/', list_all_jobs, name="list_all_jobs"),
    path('ai_jobs/', ai_jobs, name="ai_jobs"),
    path('job_detail/<int:job_id>/', job_detail, name="job_detail"),
    path('account/', include('Account.urls', namespace='account')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', registration_view, name="register"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_changedone.html'),
    name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_resetdone.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_resetform.html'),
        name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_resetcomplete.html'),
        name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.conf import settings

class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200,null=True)
    email = models.CharField(max_length=200,null=True)
    phone = models.CharField(max_length=12,null=True,unique=True)
    def __str__(self):
        return self.name
    
def get_post_image_filepath(self, filename):
    return 'post_images/' + str(self.pk) + '/post_image.png'
    
class Posting(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200,null=True)
    abstract = models.TextField(null=True)
    detail_description = models.TextField(null=True)
    skills = models.CharField(max_length=200,null=True)
    budget = models.CharField(max_length=200,null=True)
    image = models.ImageField(max_length=255,upload_to=get_post_image_filepath,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model
from Account.models import Account
from home.models import Posting
from dotenv import load_dotenv
from langchain.text_splitter import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import DeepLake
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from langchain_openai import ChatOpenAI
import os
load_dotenv()
user=get_user_model()

openai_api_key = os.getenv('OPENAI_API_KEY')
def get_pdf_text():
    text = """Problem Statement:
Establish a platform that connects freelancers with potential clients, enhancing visibility and
opportunities.

Solution:

Title: Bridging the Gap: How Our Platform Connects Freelancers with Clients Seamlessly

In todays dynamic digital landscape, the demand for freelance services is booming. From graphic design
to content creation, businesses are increasingly turning to freelancers to meet their diverse needs.
However, with this surge in demand comes a new set of challenges for both freelancers and clients alike.
Finding the right match can be time-consuming and frustrating, often leading to missed opportunities and
underutilized talents.

Enter our innovative platform, designed to bridge the gap between freelancers and clients, revolutionizing
the way they connect and collaborate. Heres how it works:

* Comprehensive Profile Creation: Freelancers are invited to create detailed profiles showcasing their
skills, experience, and portfolio. Clients, on the other hand, can create profiles outlining their specific
project requirements and expectations.

* Advanced Search and Filtering: Our platform utilizes advanced search algorithms to match freelancers
with projects that align with their expertise and interests. Clients can easily filter through profiles based on
criteria such as skills, experience level, and budget.

* Real-time Communication: Once a potential match is identified, our platform facilitates seamless
communication between freelancers and clients through integrated messaging tools. This allows for
efficient collaboration and ensures that both parties are on the same page from the outset.

* Resource Center and Support: In addition to facilitating connections, our platform serves as a valuable
resource center for freelancers and clients alike. From best practices for project management to tips for
negotiating contracts, our platform offers comprehensive support every step of the way.

* Continuous Improvement: We are committed to continuously improving our platform based on user
feedback and industry trends. Through regular updates and enhancements, we strive to provide the best
possible experience for freelancers and clients alike.

In conclusion, our platform offers a user-friendly and efficient solution to the challenges of connecting
freelancers with clients. By leveraging cutting-edge technology and fostering a supportive community, we
empower freelancers to showcase their talents and help clients find the perfect match for their projects.
Join us and experience the future of freelance collaboration today!

 """
    return text

def get_text_chunks(text):
    text_splitter = CharacterTextSplitter(
        separator = "\n",
        chunk_size=1000,
        chunk_overlap=150,
        length_function=len
    )
    chunks = text_splitter.split_text(text)
    return chunks

def get_vectorstore(text_chunks):
    dataset_path = "./my_deeplake/"
    embeddings = OpenAIEmbeddings()
    vectorstore = DeepLake.from_texts(text_chunks,dataset_path=dataset_path, embedding=embeddings)
    return vectorstore

def get_conversation_chain(vectorstore,user_question):
    llm = ChatOpenAI(model="gpt-3.5-turbo")
    memory = ConversationBufferMemory(memory_key='chat_history')
    conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        memory=memory,
        retriever=vectorstore.as_retriever(),
    )
    user_question += 'Draft the response in less than 50 words.'
    response = conversation_chain({'question':user_question})
    return response['answer']

def home(request):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    if request.method == 'POST':
        user_question = request.POST['chatinput']
        raw_text = get_pdf_text()
        text_chunks = get_text_chunks(raw_text)
        vectorstore = get_vectorstore(text_chunks)
        response = get_conversation_chain(vectorstore,user_question)
        context['content'] = response
        DeepLake.force_delete_by_path("./my_deeplake/")

    return render(request, 'home/home.html',context)

def job_posting(request):
    user_id = request.user.id
    customer = request.user.customer
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    if request.method == 'POST':
        Posting.objects.create(
            customer=customer,
            title=request.POST['title'],
            abstract=request.POST['abstract'],
            detail_description=request.POST['description'],
            skills=request.POST['skills'],
            budget=request.POST['budget'],
            image=request.FILES['image']
        )
        return redirect('home')
    return render(request, 'home/job_posting.html',context)

def list_jobs(request):
    user_id = request.user.id
    customer = request.user.customer
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass
    context['jobs'] = Posting.objects.filter(customer=customer)
    return render(request, 'home/list_jobs.html',context)

def list_all_jobs(request):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    if request.method == 'POST':
        context['jobs'] = Posting.objects.filter(title__contains=request.POST['search'])
    else:
        context['jobs'] = Posting.objects.all()
    return render(request, 'home/list_all_jobs.html',context)

def job_detail(request,job_id):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass
    context['job'] = Posting.objects.get(pk=job_id)
    return render(request, 'home/job_detail.html',context)

def ai_jobs(request):
    user_id = request.user.id
    context = {}
    try:
        account = Account.objects.get(pk=user_id)
        if account:
            context['profile_image'] = account.ImageURL
    except:
        pass

    return render(request, 'home/ai_jobs.html',context)

home/templates/home/snippets/footer.html
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" id="footer" data-wow-delay="0.1s">
    <div class="container py-5" style="display: flex;justify-content: center;">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Company</h5>
                <a class="btn btn-link text-white-50" href="">About Us</a>
                <a class="btn btn-link text-white-50" href="">Contact Us</a>
                <a class="btn btn-link text-white-50" href="">Our Services</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Quick Links</h5>
                <a class="btn btn-link text-white-50" href="">About Us</a>
                <a class="btn btn-link text-white-50" href="">Contact Us</a>
                <a class="btn btn-link text-white-50" href="">Our Services</a>
            </div>
            <div class="col-lg-4 col-md-6" style="width: 300px;">
                <h5 class="text-white mb-4">Contact</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>182 ,subramanium road, R.S puram, Coimbatore</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+91 9677741597</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>saisidharthan17@gmail.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container" style="display: flex;justify-content: center;">
        <div class="copyright">
            <div class="row">
                <div class="col-md-12 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">FreelanceGo</a>, All Right Reserved. 
                    
                    Designed By <a class="border-bottom" href="#">Bit Developers</a>
                </div>
            </div>
        </div>
    </div>
</div>

home/templates/home/snippets/navbar.html
{% load static %}
<nav class="navbar sticky-top" style="background-color: #212529;height: 70px;">
    <div class="container" style="display: flex;justify-content: space-between;">
        <ul class="nav-links">
            <li> 
                <a for="logo" class="logo-label" style="font-size: 28px;color: #e8ce4d;font-weight: 500;" href="{% url 'home' %}">FreelanceGo</a>
                {% if request.user.is_authenticated %}
                    {% if request.user.user_type == 'f' %}
                    <a class="text-white" style="text-decoration: none;font-weight: 325;margin-left: 10px;" href="{% url 'list_all_jobs' %}">Job Posts</a>
                    {% else %}
                    <a class="text-white" style="text-decoration: none;font-weight: 325;margin-left: 10px;" href="{% url 'job_posting' %}">Post Project</a>
                    <a class="text-white" style="text-decoration: none;font-weight: 325;margin-left: 10px;" href="{% url 'list_jobs' %}">My Posts</a>
                    {% endif %}
                {% endif %}
            </li>
        </ul>
        <ul class="nav-signups">
            <li>
                {% if request.user.is_authenticated %}
                <div class="d-flex flex-row">
                    <h5 class="mt-1 mr-3 font-weight-normal justify-content-start p-2">
                        <a class="text-white" style="text-decoration: none;font-weight: 325;font-size: 22px;" href="{% url 'account:view' user_id=request.user.id %}">Account</a>
                        <a class="text-white" style="text-decoration: none;font-weight: 325;font-size: 22px;margin-left: 10px;" href="{% url 'logout' %}">Logout</a>
                    </h5>
                </div>
                {% else %}
                <div class="d-flex flex-row">
                    <h5 class="mt-1 mr-3 font-weight-normal justify-content-start p-2">
                        <a class="text-white" style="text-decoration: none;font-weight: 325;font-size: 22px;" href="{% url 'login' %}">Login</a>
                        <a class="text-white" style="text-decoration: none;font-weight: 325;font-size: 22px;margin-left: 10px;" href="{% url 'register' %}">Register</a>
                    </h5>
                </div>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>